
server:
  public:
    listen:
      ip: 127.0.0.1
      port: 8080
  secure:
    mutualAuth: true
    listen:
      ip: 127.0.0.1
      port: 9090
  ocsp: 
    domain: 'localhost'
    port: 8443
  crl: 
    domain: 'localhost'
    port: 8080

pkidir: 'D:/Perso/BACKUP/pki/'

users:
  issuer:
    root: 'root'
    name: 'intermediate-client'

certificates:
  lifetime_default: 1
  lifetime_max: 365
  ca_lifetime_default: 3650
  api:
    directory: 'apicert'
    name: 'api'
    passphrase: 'ddddddd'
